name: Test

on:
  workflow_dispatch: # trigger manually

# globals
env:
  # knora-api
  KNORA_API_REPO: dasch-swiss/knora-api
  KNORA_API_BRANCH: main
  KNORA_API_DIR: knora-api
  
  
jobs:
  build:
    runs-on: macOS-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites   # cf. https://docs.knora.org/04-publishing-deployment/getting-started/
        run: sh ./.github/knora-prerequisites.sh
      
      - name: Checkout KNORA_API_REPO into KNORA_API_DIR
        uses: actions/checkout@v2
        with:
          repository: ${{ env.KNORA_API_REPO }}
          ref: ${{ env.KNORA_API_BRANCH }}
          path: ${{ env.KNORA_API_DIR }}

      - name: Make init-db-test
        working-directory: ${{ env.KNORA_API_DIR }}
        run: make init-db-test
      
      - name: Make stack-up
        working-directory: ${{ env.KNORA_API_DIR }}
        run: make stack-up
