name: Test

on:
  workflow_dispatch: # trigger manually

jobs:
  build:
    runs-on: macOS-10.15

    steps:
      - name: Prerequisites   # cf. https://docs.knora.org/04-publishing-deployment/getting-started/
        run: echo "Installing prerequisites"
        
      - name: Check git
        if: always()
        run: git --version

      - name: Check and update Bazelisk
        if: always()
        run: |
          bazelisk version
          if [ npm -g list @bazel/bazelisk] ; then
            echo "Hurray, already installed"
          else
            echo "Needs to be installed"
          fi
          # npm -g view @bazel/bazelisk
          npm -g update @bazel/bazelisk
      
      - name: Check Docker
        if: always()
        run: |
          # env | grep DOCKER
          # see https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
      
      - name: Check and update homebrew 
        if: always()
        run: |
          brew --version
          brew update

      - name: Switch to JAVA 11 (AdoptOpenJDK)
        if: always()
        run: |
          # brew tap AdoptOpenJDK/openjdk
          # brew cask install AdoptOpenJDK/openjdk/adoptopenjdk11
          export JAVA_HOME=`/usr/libexec/java_home -v 11`
          java -version
                
      - name: Install expect
        if: always()
        run: brew install expect
        
      - name: Install sbt
        if: always()
        run: brew install sbt
          
      - name: Make stack-up
        if: always()
        run: |
          # make init-db-test
          # make stack-up
          
          
