name: Test

on:
  workflow_dispatch: # trigger manually

jobs:
  build:
    runs-on: macOS-10.15

    steps:
      - name: Prerequisites   # cf. https://docs.knora.org/04-publishing-deployment/getting-started/
        run: echo "Installing prerequisites"
        
      - name: Check git
        if: always()
        run: git --version

      - name: Check and update Bazelisk
        if: always()
        run: |
          # npm list --depth 0 -g
          npm -g v @bazel/bazelisk
          if npm -g ls | grep @bazel/bazelisk ; then
            echo "bazelisk already installed."
          else
            # if not, install bazelisk
            echo "No bazelisk installed."
          fi 
          # npm list -g --depth 0 bazelisk
          # npm update -g @bazel/bazelisk
      
      - name: Check Docker
        if: always()
        run: |
          env | grep DOCKER
          # see https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
      
      - name: Check and update homebrew 
        if: always()
        run: |
          brew --version
          brew update

      - name: Switch to JAVA 11 (AdoptOpenJDK)
        if: always()
        run: |
          # brew tap AdoptOpenJDK/openjdk
          # brew cask install AdoptOpenJDK/openjdk/adoptopenjdk11
          export JAVA_HOME=`/usr/libexec/java_home -v 11`
          java -version
                
      - name: Install expect
        if: always()
        run: brew install expect
        
      - name: Install sbt
        if: always()
        run: brew install sbt
          
      - name: Make stack-up
        if: always()
        run: |
          # make init-db-test
          # make stack-up
          
          
