name: Test

on:
  workflow_dispatch: # trigger manually

jobs:
  build:
    runs-on: macOS-10.15

    steps:
      - name: Prerequisites   # cf. https://docs.knora.org/04-publishing-deployment/getting-started/
        run: echo "Installing prerequisites"
        
      - name: Check git
        run: git --version

      - name: Check and update homebrew 
        run: |
          brew --version
          brew update

      - name: Switch to JAVA 11 (AdoptOpenJDK)
        run: |
          # brew tap AdoptOpenJDK/openjdk
          # brew cask install AdoptOpenJDK/openjdk/adoptopenjdk11
          export JAVA_HOME=`/usr/libexec/java_home -v 11`
          java -version
                
      - name: Install expect
        run: brew install expect
        
      - name: Install sbt
        run: brew install sbt
        
      - name: Install Bazel
        run: npm install -g @bazel/bazelisk
          
      - name: Make stack-up
        run: |
          # make init-db-test
          # make stack-up
          
          
