name: Salsah Model Extraction

on:
  workflow_dispatch: # trigger manually

# globals
env:
  SCRIPT_DIR: 1_salsah-model-extraction


jobs:
  extract_salsah_model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install langdetect requests
          
      - name: Run extraction script
        working-directory: ${{ github.workspace }}/${{ env.SCRIPT_DIR }}
        run: python SalsahModelToJson.py

      - name: Verify
        run: ls -R
      
      - name: Commit file
        run: |
          count=$(ls -1 *.json 2>/dev/null | wc -l)
          echo "Found $count JSON files"
          
          if [ $count > 1 ]; then
            echo "### Need to archive older files"
            # mv artifacts/$CLI_BUILD/Anton\ Webern\ Gesamtausgabe_*.json $GITHUB_WORKSPACE/$SCRIPT_DIR/archive
          else
            echo "### No other file here..."
          fi
          

# TODO: upload artifact
