name: Salsah Model Extraction

on:
  workflow_dispatch: # trigger manually

# globals
env:
  SCRIPT_DIR: 1_salsah-model-extraction


jobs:
  extract_salsah_model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install langdetect requests
          
      - name: Run extraction script
        working-directory: ${{ github.workspace }}/${{ env.SCRIPT_DIR }}
        run: | 
          pwd
          ls -alh
          python SalsahModelToJson.py

      - name: Verify
        run: ls -R

# TODO: upload artifact
