name: Salsah Model Extraction

on:
  workflow_dispatch: # trigger manually

# globals
env:
  SCRIPT_DIR: 1_salsah-model-extraction
  OLD_JSON_FILE: ""
  NEW_JSON_FILE: ""


jobs:
  extract_salsah_model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/${{ env.SCRIPT_DIR }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run extraction script
        working-directory: ${{ github.workspace }}/${{ env.SCRIPT_DIR }}
        run: python SalsahModelToJson.py

      - name: Verify
        run: ls -R
      
      - name: Commit file
        working-directory: ${{ github.workspace }}/${{ env.SCRIPT_DIR }}
        run: |
          count=$(ls -1 *.json 2>/dev/null | wc -l)
          echo "Found $count JSON files"
          
          if [ $count -gt 1 ]; then
            echo "### Need to archive older files"
            for file in *.json; do 
              echo "OLD_JSON_FILE=$file" >> $GITHUB_ENV
              echo "Old Json File:"
              echo $OLD_JSON_FILE
            done
            # mv artifacts/$CLI_BUILD/Anton\ Webern\ Gesamtausgabe_*.json $GITHUB_WORKSPACE/$SCRIPT_DIR/archive
          else
            echo "### No other file here..."
            for file in *.json; do 
              echo "NEW_JSON_FILE=$file" >> $GITHUB_ENV
              echo "New Json File:"
              echo $NEW_JSON_FILE 
            done
          fi
        
      - name: Verify
        run: |
          echo "Old Json File:"
          echo $OLD_JSON_FILE
          echo "New Json File:"
          echo $NEW_JSON_FILE
          

# TODO: upload artifact
